widowx_reacher-v1:
  # env_wrapper: utils.wrappers.TimeFeatureWrapper
  # policy_kwargs: "dict(log_std_init=-2, ortho_init=False)"
  n_timesteps: 500000
  normalize: true
  n_envs: 8
  policy: 'MlpPolicy'
  learning_rate: 0.0007
  n_steps: 5
  gamma: 0.99
  gae_lambda: 1.0
  ent_coef: 0.0
  vf_coef: 0.5 
  max_grad_norm: 0.5 
  rms_prop_eps: 0.00005
  use_rms_prop: True
  use_sde: False
  sde_sample_freq: -1
  normalize_advantage: False
  create_eval_env: False 
  policy_kwargs: None
  device: 'auto'
  _init_setup_model: True
  

widowx_reacher-v3:
  # env_wrapper: utils.wrappers.TimeFeatureWrapper
  # policy_kwargs: "dict(log_std_init=-2, ortho_init=False)"
  n_timesteps: 500000
  normalize: true
  n_envs: 8
  policy: 'MlpPolicy'
  learning_rate: 0.0007
  n_steps: 5
  gamma: 0.99
  gae_lambda: 1.0
  ent_coef: 0.0
  vf_coef: 0.5 
  max_grad_norm: 0.5 
  rms_prop_eps: 0.00005
  use_rms_prop: True
  use_sde: False
  sde_sample_freq: -1
  normalize_advantage: False
  create_eval_env: False 
  policy_kwargs: None
  device: 'auto'
  _init_setup_model: True